### ISSUE TITLE
Preprocessing for resnet model

### ISSUE THREAD

**Issue by Nerdyvedi** [allo-/virtual_webcam_background#41]
Hi, 
The same preprocessing steps do not work for resnet model. Could you share what changes need to be made when we are using resnet instead of mobilenet?

Thank you

**Comment by allo-** [comment]
The preprocessing is already implemented.

You need to set `model: resnet50` in your config when using resnet. and make sure you use a valid stride/multiplier for resnet. The halo plugin may not work due to a different model (and debug_show_heatmap uses different indices), but the segmentation itself is implemented and tested.

**Comment by Nerdyvedi** [comment]
@allo- Thanks.
I am able to get good results with float model, Do you know what is the issue when using the quantised model ?It is not giving the correct result.
